name: Java CI (build & test)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Levanta MongoDB para los tests de integración / @SpringBootTest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd="mongosh --username root --password example --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    # Variables que tu app lee (tal y como en application.properties)
    env:
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB: tasksdb_test
      MONGO_USER: root
      MONGO_PASS: example
      MONGO_AUTHDB: admin

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & test with Maven
        working-directory: tasks-svc
        run: mvn -B -ntp verify

      - name: Upload test reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: tasks-svc/target/surefire-reports/